# -*- coding: utf-8 -*-
"""Breast Cancer Detection: Logistic Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0eirakXEezd9XYitWxmcXE1dPTQ4RhL

# Logistic Regression

## Importing the libraries
"""

import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('/content/breast_cancer.csv')

X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split

trainX, testX, trainY, testY = train_test_split(X, y, test_size= 0.2, random_state=0)

"""## Training the Logistic Regression model on the Training set"""

from sklearn.linear_model import LogisticRegression
model =  LogisticRegression() 
model.fit(trainX, trainY)

"""## Predicting the Test set results"""

pred_y = model.predict(testX)

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(testY, pred_y)
print(cm)

"""## Computing the accuracy with k-Fold Cross Validation"""

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X = trainX, y = trainY, cv =10)
print("Cross Validation Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Cross Validation Standard Deviation: {:.2f} %".format(accuracies.std()*100))